# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Adhoc Editor
tagline:             'Adhoc Editor'
description:         'Welcom to Adhoc Editor'
url:                 https://github.com/adhoceditor
baseurl:             'http://adhoceditor.github.io/'
paginate:            5

# About/contact
author:
  name:              Ping Zhang
  email:             pingzh@umich.edu

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

markdown: redcarpet
